### ISSUE TITLE
App wake up from cold boot?

### ISSUE THREAD

**Issue by hnguyen48206** [aparajita/capacitor-ios-silent-notifications#1]
Hi Sir,

May I know if this plugin work in case of the app does not in active at all (not foreground or background)? and then when the notification comes, we recieve it and launch the app (without user interaction)?

Thank you.

**Comment by aparajita** [comment]
No, if the app is not running at all, no silent notification can be received. If the user forcefully terminates an app, they obviously do not want the app to run, and they would consider it very bad behavior if you then silently launched the app without their consent or knowledge.
